### PR TITLE
attribute_changed? is deprecated as of Rails 5.1

### PR DESCRIPTION
**Pull request by redox**
https://github.com/rails/rails/pull/25337#issuecomment-225166796

### CODE REVIEW

**Comment by redox** [comment]
Test failing because of https://github.com/algolia/algoliasearch-rails/pull/264

**Comment by joshfng** [comment]
Curious if there are any blockers on this or if I can help out in any way

**Comment by joshfng** [comment]
Is there anything we can do to help get this merged? Our rails 5 app is pinned to this branch in order to work properly and we face issues when the git ref changes due to the branch being force pushed

**Comment by jeromedalbert** [comment]
Are the tests the only thing stopping this PR from being merged? It looks like the only thing that doesn't work in this PR is https://github.com/algolia/algoliasearch-rails/pull/263/files#diff-dfaec67e907148ea8211e17340f0f30cR897 because `ActiveRecord::Version` does not exist.

I have made PR https://github.com/algolia/algoliasearch-rails/pull/325 to fix this.

**Comment by jeromedalbert** [comment]
@redox Are the tests the only thing stopping this PR from being merged? It looks like the only thing that doesn't work in this PR is https://github.com/algolia/algoliasearch-rails/pull/263/files#diff-dfaec67e907148ea8211e17340f0f30cR897 because ActiveRecord::Version does not exist.

If so, I have made PR #325 to fix this.

**Comment by redox** [comment]
@julienbourdeau do you mind taking over? @jeromedalbert is right about `ActiveRecord::VERSION`.

**Comment by julienbourdeau** [comment]
@redox Yes sure! 

I rebased the PR yesterday and indeed it failed on older version of Rails, I misread I thought the uppercase version wasn't defined either. 👌 

Thanks @jeromedalbert! I'll close this one if favor of yours

**Pull request closed without merging**
