### PR TITLE
Algolia v2 symbolizes keys

### PR DESCRIPTION
**Pull request by bvogel**
| Q                 | A
| ----------------- | ----------
| Bug fix?          | yes
| New feature?      |no
| BC breaks?        | no 
| Related Issue     | None
| Need Doc update   | yes

## Describe your change

force the setting of `symbolize_keys: false` as this project breaks without this setting

## What problem is this fixing?

undefined method .map for nil in https://github.com/algolia/algoliasearch-rails/blob/master/lib/algoliasearch-rails.rb#L690

### CODE REVIEW

**Comment by bvogel** [comment]
@DevinCodes if you could take a look at this once you're back from vacation, this would be very much appreciated.

**Review by DevinCodes — APPROVED** [review]
Thank you @bvogel ! I'll try to release this later today.

**Comment by DevinCodes** [comment]
This is out in [v2.1.2](https://rubygems.org/gems/algoliasearch-rails/versions/2.1.2). Thank you again!

**Comment by bvogel** [comment]
Thank you to you!

**Pull request merged**
