### PR TITLE
Add ordering of attributes comment.

### PR DESCRIPTION
**Pull request by joshuapinter**
Most important to least important. 

I spent a good deal of time looking into Custom Ranking when I was simply trying to specify which attributes are more important than other attributes. This comment should help others clearly figure that out.

### CODE REVIEW

**Comment by redox** [comment]
Hmmmm, not exactly. This list only defines the list of attributes to send to Algolia. Then, to control their importance you need to configure the `attributesToIndex` setting.

You'll end up with something like:

```ruby
class MyModel
  include AlgoliaSearch
  algoliasearch do
    attributes :first_name, :last_name, :email
    attributeToIndex ['last_name', 'first_name'] # list of searchable attributes (by order or importance)
  end
end
```

I'm updating the documentation to make it clearer.

**Comment by joshuapinter** [comment]
Ah, gotcha. Glad I asked.

So, is defining `attributes` necessary if you're not trying to send any additional attributes outside of those you want to be searchable in `attributeToIndex`?

**Comment by joshuapinter** [comment]
Also, it's `attributesToIndex` _(with an **s**)_ for those that might land here.

**Comment by redox** [comment]
Good catch, with an `s`. Is this new documentation section explicit enough?

**Comment by joshuapinter** [comment]
Made some comments on the commit. Probably should have asked my questions on this thread, though. Sorry.

**Comment by joshuapinter** [comment]
I've got this thing humming now, thanks! :+1:

**Pull request closed without merging**
