### PR TITLE
Don't use deprecated attribute_changed?

### PR DESCRIPTION
**Pull request by jeromedalbert**
| Q                 | A
| ----------------- | ----------
| Bug fix?          | no
| New feature?      | no 
| BC breaks?        | no     
| Related Issue     | Fix #263
| Need Doc update   | no

## Describe your change

This is the same code as PR https://github.com/algolia/algoliasearch-rails/pull/263 (which has been stale for more than a year), but fixed with all tests hopefully passing.

## What problem is this fixing?

PR https://github.com/algolia/algoliasearch-rails/pull/263 used `ActiveRecord::Version` which doesn't exist: only `ActiveRecord::VERSION` exists. My PR fixes that.

The end goal of both this PR and the original PR is to use non-deprecated fields.

### CODE REVIEW

**Comment by julienbourdeau** [comment]
@jeromedalbert Yes sorry about that. I'm looking into it, I dont understand why it's timing out 😭  It seems to happen a lot more in rails repo than other repo.

I think this is the most urging PR, so I think I'll release my first patch version tomorrow with it and release the rest of the PR/issues per batch.

**Comment by julienbourdeau** [comment]
Thank you for this contribution! 🚀

**Comment by jeromedalbert** [comment]
@julienbourdeau Thanks!

It looks like you minted v1.20.5 of this gem on GitHub, but it hasn't been pushed to [RubyGems yet](https://rubygems.org/gems/algoliasearch-rails).

So we're using `master` directly for now and haven't had any problems. Have a great Christmas

**Comment by vincentwoo** [comment]
Shipping this change without the necessary documentation changes was a huge mistake.

**Comment by julienbourdeau** [comment]
It was, sorry @vincentwoo 🙏 

@jeromedalbert If you can find time to review #338 I'd really appreciate your opinion on it.

**Pull request merged**
