### PR TITLE
Replaced "noop" with "not run".

### PR DESCRIPTION
**Pull request by joshuapinter**
Not sure if that's an inside joke or not (I looked it up on Urban Dictionary, regardless :) but this makes it more clear.

### CODE REVIEW

**Comment by redox** [comment]
No that's cool, thanks! :+1:

**Comment by joshuapinter** [comment]
:+1: 

Btw, this is one of the best platforms and supporting gems that I have every used. You guys have done an incredible job with all of this.

**Comment by redox** [comment]
Thank you for the positive feedback @joshuapinter, we really appreciate. Being able to provide working (tests + code coverage + code climate + changelog) API clients is something we really care about. To be honest, bootstrapping all those API clients (12 right now) was pretty painful at the beginning but now it's priceless!

**Comment by joshuapinter** [comment]
It doesn't go unappreciated! Thanks again!

thumbsup

**Pull request merged**
