### PR TITLE
Prevent an extra get_settings call even if check_settings is false

### PR DESCRIPTION
**Pull request by annikoff**
| Q                 | A
| ----------------- | ----------
| Bug fix?          | yes
| New feature?      | no
| BC breaks?        | no     
| Related Issue     | no
| Need Doc update   | no

## Describe your change

Added condition to check if `check_settings` is `true` before retrieving index settings.

## What problem is this fixing?

An extra call to get index settings performs even if `check_settings` is `false` as it described here https://www.algolia.com/doc/framework-integration/rails/index-configuration/index-settings/?language=ruby#synchronizing-settings

### CODE REVIEW

**Comment by annikoff** [comment]
Hello. Could this PR be rejected or merged?

**Comment by annikoff** [comment]
@redox Could anyone take a look at this, please?

**Comment by redox** [comment]
@DevinCodes are you able to take over?

**Review by DevinCodes — APPROVED** [review]
Thank you @annikoff for the contribution, I'll release this later today!

**Comment by annikoff** [comment]
@DevinCodes Great. Thanks

**Comment by DevinCodes** [comment]
This is released in [version 2.1.3](https://rubygems.org/gems/algoliasearch-rails/versions/2.1.3). Thank you again for the contribution!

**Pull request merged**
