### PR TITLE
Introduce :inherit_attributes and :inherit_settings options to reduce code duplication

### LINKED ISSUE #186: Setting Facets on Slaves
Hi just a sanity check, in the DSL, can I set `attributesForFaceting` on slaves? I have them set for each slave, v 1.13.0,  and they don't seem to be propagating to the slave indexes...

### LINKED ISSUE #296: allow add_index, inherit: true
`add_replica` already supports `inherit: true do`. It would be nice if `add_index` also supported it.

How it would work

```ruby
algoliasearch if: :published do
    attribute :title, :description

    attribute :starts_at do
      starts_at.to_i
    end

    searchableAttributes %w[title unordered(description)]
    attributesToSnippet %w[description]
    attributesForFaceting %w[filterOnly(starts_at)]

    add_replica STARTS_AT_ASC_INDEX, inherit: true do
      customRanking ['asc(starts_at)']
    end

    add_index ADMIN_INDEX_NAME, inherit: true do
      attributesForFaceting %w[state]
    end
  end
```

The idea is that `ADMIN_INDEX_NAME` would not require repeated definition of:

```ruby
    attribute :title, :description

    attribute :starts_at do
      starts_at.to_i
    end

    searchableAttributes %w[title unordered(description)]
    attributesToSnippet %w[description]
```

and it would not get the `STARTS_AT_ASC_INDEX` replica. 

I tried to replicate this behavior with:

```ruby
add_index ADMIN_INDEX_NAME, inherit: true, primary_settings: self
```

similarly to how `add_replica` works under the hood but there were certain problems with this approach. Namely `starts_at` was not using the `Proc` with `to_i` conversion.

Also there is an API documentation of Ruby client https://www.algolia.com/doc/api-client/ruby/getting-started/ and there is tutorial for Rails https://www.algolia.com/doc/api-client/rails/indices/#target-multiple-indices but I could not find a full API documentation for algoliasearch-rails to know which exact options are supported on which methods.

Or maybe you can recommend other ways to handle this scenario? Defining a method on the model and using it as attribute name, maybe?

### PR DESCRIPTION
**Pull request by julienbourdeau**
| Q                 | A
| ----------------- | ----------
| Bug fix?          | no
| New feature?      | yes    
| BC breaks?        | no     
| Need Doc update   | yes

## Describe your change

`add_replica` let you inherit index settings from the primary index. This PR add this feature to `add_index`as well.

Partially fixes #296. It only inherit settings, I have to also inherit attributes (and additional attributes) which I think is doable. It wasn't required for `add_replica`since a replica has the same content as a primary index by design.

Note that the parent index is called "primary" even for add_index, which can be misleading since it's not a primary/replica relationship. I'd rather keep this name since it seems some users are already passing the `:primary_index => self` option explicitely (see #296).

### TODO:

- [x] Inherit settings for `add_index`
- [x] Inherit settings for `add_replica`
- [x] Inherit serialization logic (attributes) for `add_index`
    - [x] Including Additional attributes (tags and geoloc)
- [ ] Ensure these changes are 100% backward compatible
- [x] Set settings for replicas of additional index - Fix #186
- [x] Additonal index don't inherit replicas

## 📝 To document

- [ ] 🆕 `Model.reindex` will set_settings on all indices of the model (incl replicas).
- [ ] New Inherit capabilities (of course)

### CODE REVIEW

**Comment by Spone** [comment]
Looking forward to this feature being released, it will allow me to DRY all my indices :)

**Comment by Spone** [comment]
This library is definitely getting no love from Algolia since 2019 :disappointed: 

What is happening @julienbourdeau?

**Comment by duhaime** [comment]
@jvenezia @francoischalifour @rayrutjes any chance this could be reviewed? 🙏

This functionality really helps when a user wants to push the same attributes to multiples indices without replicating the attribution logic...

**Comment by duhaime** [comment]
For others who end up here wanting to remove reused code, another path forward is to [use a concern that defines shared logic in a Proc block](https://github.com/algolia/algoliasearch-rails/issues/423).

**Comment by julienbourdeau** [comment]
Thanks Douglas!

**Pull request closed without merging**
