### PR TITLE
Fix ActiveJob::DeserializationError issue

### LINKED ISSUE #359: AlgoliaJob for the deleted record always rise ActiveJob::DeserializationError
- Rails version: 4.2.11.1
- Algolia Rails integration version: 1.18.0
- Algolia Client Version: 1.12.5
- Language Version: 2.4.6

### Description

Asynchronous index update enqueues a job with the specific object instance as a parameter. This specific object cannot be deserialized from the parameter during job processing for the deleted record. An asynchronous index update job for the deleted record will always fail.

A possible solution according to job guidelines could be to enqueue a job with the record identifier as a parameter, not the instance itself. Decouple index update logic from the model and use this logic inside job. We need only an ID to delete a record from the index, not the object itself.

### Steps To Reproduce

1. Create a simple model with the Algolia included and configured to update the index asynchronously
```
class School
  include Mongoid::Document
  include AlgoliaSearch

  field :title,                type: String
  field :description,          type: String
  field :street,               type: String
  field :zipcode,              type: String
  field :city,                 type: String

  algoliasearch per_environment: true, enqueue: true do
    attributes :title, :street, :zipcode, :city
  end
end
```
2. Create an object, destroy an object. 
```
s = School.create(
  title: 'Fancy',
  street: 'Claude Bernard',
  zipcode: '75005',
  city: 'Paris'
)
s.destroy
```
3. Ensure the job fails within your asynchronous worker
```
ActiveJob::DeserializationError: Error while trying to deserialize arguments:...
```

### PR DESCRIPTION
**Pull request by zhukovpe**
| Q                 | A
| ----------------- | ----------
| Bug fix?          | yes
| New feature?      | no
| BC breaks?        | yes     
| Related Issue     | Fix #359 
| Need Doc update   | no

## Describe your change

Change job arguments to receive a record identifier and a model class name (for index info) as a parameter instead of a model instance. Add a method to remove a record from algolia index by id.

## What problem is this fixing?

Asynchronous index update enqueues a job with the specific object instance as a parameter. This specific object cannot be deserialised from the parameter during job processing for the deleted record. An asynchronous index update job for the deleted record will always fail.

## Breaking changes
Previously deployed AlgoliaJob will fail if executed with the new version

### CODE REVIEW

**Comment by annikoff** [comment]
I suppose it has some breaking changes because if you have enqueued some `AlgoliaJob` jobs they will fail after version update.

**Comment by lukad03** [comment]
Any timeline for review of this?

**Comment by marckohlbrugge** [comment]
Could this (or a similar fix) please be merged?

Right now the gem is basically broken when it comes to removing records from the index.

**Comment by chloelbn** [comment]
Hi @marckohlbrugge , @lukad03 and @zhukovpe !
As we can't introduce BC break in fixes, this PR can't be merged as-is. It also introduces a lot of refactoring which, even if it's a really good idea considering the code base, is not the scope of this.
To be able to provide a solution for this problem, a new PR has to be made to fix the issue and only the issue, in a backward-compatible way. The ressources are a bit limited right now and we can't provide an ETA to resolve the issue on our side. However, if you wish to quicken this fix, you can provide a new PR anytime and we'll review it asap.

Thanks for your understanding!

**Comment by duhaime** [comment]
@chloelbn does this library have a pattern to remove objects from an algolia index _after the record has been deleted from the db_? 

Specifically, is there a good way to get the object id of a record in a particular index after that record has been deleted from the db?

**Pull request closed without merging**
