### PR TITLE
fix ruby 3.0 default splat behavior

### PR DESCRIPTION
**Pull request by bvogel**
| Q                 | A
| ----------------- | ----------
| Bug fix?          | yes
| New feature?      |no    
| BC breaks?        | no     
| Related Issue     | Fix #...  
| Need Doc update   |no

## Describe your change

Ruby 3.0 will not splat arguments on default

## What problem is this fixing?

wrong number of arguments (given 2, expected 0..1)

### CODE REVIEW

**Comment by bvogel** [comment]
@chloelbn @redox as I can't seem to see what is failing, could you point me in the right direction to get the checks to pass?

**Comment by bvogel** [comment]
@chloelbn @redox any chance to get someone look at this and https://github.com/algolia/algoliasearch-rails/pull/400 - we would really need that to be able to upgrade to ruby 3

**Comment by redox** [comment]
@DevinCodes are you able to take a look?

**Comment by bvogel** [comment]
@DevinCodes please disregard this PR, as I broke stuff when force pushing to my branch. the correct PR for v1 is on #402, the one for v2/master still is valid on #400

**Comment by DevinCodes** [comment]
I’ll take a look on Monday, I’m busy moving atm so I won’t have time until then!

**Comment by DevinCodes** [comment]
Closing this PR as per your message. Your other PRs have been merged, we'll release the changes later today!

**Pull request closed without merging**
