### PR TITLE
feat(replicas): new `inherit` parameter

### PR DESCRIPTION
**Pull request by Jerskouille**
Adds a `forward_to_replicas` parameter to the main `algoliasearch`block.

### CODE REVIEW

**Comment by Jerskouille** [comment]
cc @olance

**Comment by redox** [comment]
Hmmmm, I don't think this will work because we'll keep overriding the replicas settings with the master settings :/

**Comment by Jerskouille** [comment]
The build is fixed on master, this was rebased and force pushed, I'm expecting the tests to finally pass.

I've updated the code to expose an `inherit` option on the replicas instead. WDYT of this new version @redox ?

**Comment by redox** [comment]
That's awesome @Jerskouille 👍

**Pull request merged**
